services:
  db:
    container_name: "task_db"
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: task_db
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy

  ktor:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9292:9292"
    # (optionally add environment variables so Ktor picks up the correct DB port):
    environment:
      DATABASE_URL: "jdbc:postgresql://task_db:5432/task_db"

volumes:
  pgadmin_data:
  db_data:
