ktor:
    application:
        modules:
            - com.sapp.ApplicationKt.module
    deployment:
        port: 9292
storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://task_db:5432/task_db"
    user: "postgres"
    password: "1234"